version: "3.9"

services:
  app:
    container_name: chatgpt-node-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50001:3000"
    volumes:
      - .:/usr/app
    command: npm start
    env_file:
      - .env
