version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50001:3000"
    volumes:
      - .:/usr/app
    command: npm start
    env_file:
      - .env
    networks:
      - dev-env
networks:
  dev-env:
    external: true